### ISSUE TITLE
配置文件

### ISSUE THREAD

**Issue by duokebei** [chainreactors/spray#12]
作者您好：
    spray该工具使用了一下，并看了文档，发现并没有像feroxbuster这种的配置文件，请问后续会出吗？

**Comment by M09Ic** [comment]
靠命令行操作spray确实有点复杂， 后续会考虑添加配置文件。

**Comment by M09Ic** [comment]
现在已经支持, 请下载最新版本 https://github.com/chainreactors/spray/releases/tag/v0.9.3
