### ISSUE TITLE
如何过滤相同响应长度内容

### ISSUE THREAD

**Issue by cqrlhz** [chainreactors/spray#14]
![image](https://github.com/chainreactors/spray/assets/63200706/311be3f8-a829-4102-9dd1-77afcb9d949b)

**Comment by M09Ic** [comment]
如果405均为无效结果， 可以将405状态码均为无效结果。 可以将405加到黑名单中, 例如`--black-status 405`. 

如果只是想过滤掉长度为2597的数据， 可以使用expr过滤器 `--filter 'current.Status == 405 && current.BodyLength == 2597'`

**Comment by M09Ic** [comment]
粗略看来， 这个api站点对错误处理有些问题，使用`--fuzzy-status +405` 将405状态码加入到fuzzy过滤中, 也能解决这个问题. 

spray的用法并不固定, 不同的场景可以制定不同的过滤策略.

**Comment by cqrlhz** [comment]
![image](https://github.com/chainreactors/spray/assets/63200706/0da108bc-faa4-410b-a52f-b1560707a4dc)
 过滤不了

**Comment by M09Ic** [comment]
图片中的结果看到405的结果好像已经被过滤了, warn的信息可以忽略, 或者-q关闭非必要信息.
