### ISSUE TITLE
如何过滤或关闭 warn

### ISSUE THREAD

**Issue by cqrlhz** [chainreactors/spray#16]
![image](https://github.com/chainreactors/spray/assets/63200706/eefef17f-1ac9-4680-9fd0-dbcd69eb60b2)

**Comment by M09Ic** [comment]
因为nginx服务器的特性，导致可能有两个默认的404页面导致的误判。 已经在计划队列中， 下个版本修复。 

spray提供了多种过滤方式， 用在不用的场景， 详情可以参考文档 https://chainreactors.github.io/wiki/spray/start/#_10

**Comment by M09Ic** [comment]
现在已经解决这个问题, 请下载最新版本 https://github.com/chainreactors/spray/releases/tag/v0.9.3
