### ISSUE TITLE
掩码生成字典爆破进度

### ISSUE THREAD

**Issue by SkinAir** [chainreactors/spray#17]
![image](https://github.com/chainreactors/spray/assets/71880910/a442514a-0070-41cd-953c-56acd0d0b82f)
如图，生成字典过大，没进度条，或者添加点-V详细进程参数之类的

**Comment by SkinAir** [comment]
![image](https://github.com/chainreactors/spray/assets/71880910/0db3dcb3-8fc7-4e8e-a226-3354c4591204)
进度出来了，但结果不是很理想，不应该只有六位小写英文吗= =！

**Comment by M09Ic** [comment]
warn的信息是用来探测是否已经被waf或者封禁的. 与实际扫描内容无关, 大概会每200请求插入一个check包.  可以-q 关闭无用信息

**Comment by M09Ic** [comment]
6位小写字母的字典可能太大了, 导致生成的时候较慢.
