### ISSUE TITLE
windows x64版本依然存在无法解析url文件的问题

### ISSUE THREAD

**Issue by lovelyjuice** [chainreactors/spray#18]
Fixed, please download new release https://github.com/chainreactors/spray/releases/tag/v0.9.1

_Originally posted by @M09Ic in https://github.com/chainreactors/spray/issues/4#issuecomment-1578691335_

试了下linux版就能用，都是0.9.1版本release里面下载的

**Comment by M09Ic** [comment]
无法复现该问题, 可以尝试新版本
