### ISSUE TITLE
都启用,应该怎么办呢？

### ISSUE THREAD

**Issue by zglaozhu** [chainreactors/spray#19]
根据有效url自动生成权限绕过字典. spray -u http://example.com -d word.txt --append-rule authbypass
根据有效url自动生成备份文件字典. spray -u http://example.com -d word.txt --append-rule filebak
如果我想都启用,应该怎么办呢？
spray -u http://example.com -d word.txt --append-rule filebak,authbypass?

**Comment by M09Ic** [comment]
很抱歉回复晚了。

`spray -u http://example.com/ -d word.txt --append-rule filebak --append-rule filebak`

**Comment by M09Ic** [comment]
现在添加了`--extract-config` 添加自定义的正则配置
