### ISSUE TITLE
启动失败 

### ISSUE THREAD

**Issue by SexyBeast233** [chainreactors/spray#2]
![image](https://github.com/chainreactors/spray/assets/34060869/aab30b7f-8e49-42fc-8fba-8c78987b1dc1)
![image](https://github.com/chainreactors/spray/assets/34060869/2148ec88-c803-4dbe-9dc0-c1cd69f9d763)
提示为 : `[-] unexpected end of JSON input` 或 `expected argument for flag `/w, /word', but got option`形式
尝试运行 以/w 或-w 或其他形式启动进程均未成功 , 以尝试编译与无编译直接运行.go  
大概是环境问题吗?> 还是说开源代码版本与文档版本有出入导致的呢
环境:win11

**Comment by SexyBeast233** [comment]
我的问题 , 我尝试了release编译完成版本 , 整成运行 😂

**Comment by SexyBeast233** [comment]
已正常运行 ,关闭is

**Comment by M09Ic** [comment]
自行编译版本报错是因为 spray依赖一个指纹仓库 https://github.com/chainreactors/gogo-templates . 

如果需要自行编译, 可以参考 README中的`https://github.com/chainreactors/spray#make` , 将最后一步的build替换为run即可.
