### ISSUE TITLE
手动配置过滤器问题

### ISSUE THREAD

**Issue by zglaozhu** [chainreactors/spray#20]
spray   -l url.txt  -d dict.txt --match 'current.Status == 200'   --dump-file result.txt

spray   -l url.txt  -d dict.txt --filter 'current.Status == 405'   -f result.txt 
没有结果
![image](https://github.com/chainreactors/spray/assets/31888299/aeb72314-05f0-4e61-ba89-5f9c8a505ef6)
去掉以后就有
![image](https://github.com/chainreactors/spray/assets/31888299/c7ab16d6-92aa-4332-a37b-b469c559965a)

**Comment by M09Ic** [comment]
`--match`为重载过滤器, 将系统内置的过滤器替换为自定义过滤器, `--filter`为从上一阶段过滤后有效的结果进行二次过滤.
