### ISSUE TITLE
--recon参数怎么用

### ISSUE THREAD

**Issue by Herbert-555** [chainreactors/spray#23]
--recon, 自动提取敏感信息, 在有效目录中提取敏感信息
说的是可在yaml中配置规则，怎么指定这个yaml文件

**Comment by M09Ic** [comment]
`--recon` 目前是启用默认配置的中的提取器。 当前配置文件位于 https://github.com/chainreactors/templates/blob/master/extract.yaml。 暂时不可以自定义

实际上`--recon`等价于使用多个extract ,例如`--extract regex1 --extract --regex2 `. 

你的需求确实提醒了我， 后续会添加允许从文件中批量加载正则表达式。

**Comment by M09Ic** [comment]
现在添加了`--extract-config` 添加自定义的正则配置。 https://github.com/chainreactors/spray/releases/tag/v0.9.4
