### ISSUE TITLE
扫描目标时报错，然后卡死

### ISSUE THREAD

**Issue by Herbert-555** [chainreactors/spray#25]
[warn] chunk encoding! buf current client FASTHTTP not support chunk decode
[warn] chunk encoding! buf current client FASTHTTP not support chunk decode
[warn] chunk encoding! buf current client FASTHTTP not support chunk decode
2024/02/18 18:02:08 worker with func exits from a panic: runtime error: index out of range [0] with length 0
2024/02/18 18:02:08 worker with func exits from panic: goroutine 40 [running]:
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1.1()
        pkg/mod/github.com/panjf2000/ants/v2@v2.7.0/worker_func.go:58 +0x10b
panic({0x5ddda0?, 0xc0000ee060?})
        $GOROOT/src/runtime/panic.go:914 +0x21f
github.com/chainreactors/parsers.(*SprayResult).Get(0x60?, {0x6116bc?, 0x60?})
        pkg/mod/github.com/chainreactors/parsers@v0.0.0-20240208143911-65866d5bbc6d/spray.go:139 +0x707
github.com/chainreactors/parsers.(*SprayResult).Additional(0xc000f20120?, {0x6116bc?, 0x23814132588?})
        pkg/mod/github.com/chainreactors/parsers@v0.0.0-20240208143911-65866d5bbc6d/spray.go:151 +0x4d
github.com/chainreactors/parsers.(*SprayResult).Format(0xc000902120, {0xc000bd7e28, 0x6, 0xc000585520?})
        pkg/mod/github.com/chainreactors/parsers@v0.0.0-20240208143911-65866d5bbc6d/spray.go:183 +0x9ee
github.com/chainreactors/spray/internal/pool.(*BrutePool).Init(0xc0006d0000)
        /home/runner/work/spray/spray/internal/pool/brutepool.go:159 +0x656
github.com/chainreactors/spray/internal.(*Runner).Prepare.func4({0x557940?, 0xc00083c280})
        /home/runner/work/spray/spray/internal/runner.go:224 +0x4fb
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1()
        pkg/mod/github.com/panjf2000/ants/v2@v2.7.0/worker_func.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run in goroutine 1
        pkg/mod/github.com/panjf2000/ants/v2@v2.7.0/worker_func.go:48 +0x5c
![图片](https://github.com/chainreactors/spray/assets/65555626/b7fcd858-5e5c-4893-be1e-c500ed8c1618)

**Comment by M09Ic** [comment]
收到问题，应该是输出指纹时特殊情况下会导致的报错，将于下个版本修复

**Comment by M09Ic** [comment]
我无法完全确认这个bug的位置，应该已于https://github.com/chainreactors/spray/releases/tag/v0.9.4 修复
