### ISSUE TITLE
--crawl 失效

### ISSUE THREAD

**Issue by sakurakishiro** [chainreactors/spray#29]
--crawl功能用不了了，加上该参数 变成默认使用github上的字典进行拼接爆破目录了
![5581709718110_ pic](https://github.com/chainreactors/spray/assets/20364431/6669df34-8cec-425a-b9a1-b2f672aaa9ec)

**Comment by M09Ic** [comment]
fixed it. https://github.com/chainreactors/spray/releases/tag/v0.9.6
