### ISSUE TITLE
Socks  5 and http proxy option

### ISSUE THREAD

**Issue by byt3hx** [chainreactors/spray#3]
Hello,

Can you please add to run the tool with  socks5 and http proxy option?

**Comment by M09Ic** [comment]
Because of spray's concurrency design, support for proxies may import unforeseen errors. A new proxy library is developing and will be updated with this one.

**Comment by M09Ic** [comment]
Thank you feature. now support proxy. https://github.com/chainreactors/spray/releases/tag/v0.9.2
