### ISSUE TITLE
过滤返回包size

### ISSUE THREAD

**Issue by TheTh1nk3r** [chainreactors/spray#30]
请问一下返回size怎么过滤啊，没找到相关参数。
类似dirsearch的 --exclude-sizes功能的

**Comment by M09Ic** [comment]
一般情况下，不需要使用到exclude-size。基于size的过滤会自动实现。如果某些特殊情况下，自动过滤失效了，可以使用--filter expr ，表达式中支持各种细粒度的参数过滤
