### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by guanglianniubi** [chainreactors/spray#35]
命令：
./spray_linux_amd64 -l url.txt -d ffuf-dict/fuck.txt --finger --bak --file-bak
爆破到一半
![图片](https://github.com/chainreactors/spray/assets/45590232/91646bbd-cdfc-4649-a121-27fe7bd1a7c3)

**Comment by guanglianniubi** [comment]
怎么输出xlsx格式呢，我用--format 1.xlsx不行

**Comment by guanglianniubi** [comment]
--match和--filter失效
![图片](https://github.com/chainreactors/spray/assets/45590232/3fe1c85d-0dab-4fd6-a54d-bdf60d8f7602)

**Comment by guanglianniubi** [comment]
--black-status 200也不行

**Comment by guanglianniubi** [comment]
-q参数只能输出一条结果
![图片](https://github.com/chainreactors/spray/assets/45590232/055a82d4-42cf-406f-b9c1-f5ea4685e1dd)

**Comment by M09Ic** [comment]
1. `--finger` 报错的bug已确认，新版本将会修复。 
2. 暂时不支持1.xlsx
3. index是初始化的一部分, 不支持过滤。 是后续扫描的基准值.

**Comment by M09Ic** [comment]
https://github.com/chainreactors/spray/releases/tag/v0.9.8
