### ISSUE TITLE
递归扫描不工作

### ISSUE THREAD

**Issue by pphuahua** [chainreactors/spray#36]
某网站二级目录包含二级目录，如下所示：
`https://abc.com/test/`
且字典里含有test，通过命令
`./spray_darwin_arm64 -u https://abc.com/ -d path.txt --black-status=401,400,404,500,503`
可以成功扫描到test目录
```
[+] [redirect] https://abc.com/test --> https://abc.com/test/ - 200 - 31851 - 325ms [XXX] [sim:19] [nginx] [XXX] 
```
且test目录下含有license页面：https://abc.com/test/license（字典里同样含有license）
但是通过配置递归无法扫描到license
`./spray_darwin_arm64 -u https://abc.com/ -d path.txt --black-status=401,400,404,500,503 --depth 2`

通过以下命令同样不可以
`/spray_darwin_arm64 -u https://abc.com/ -d path.txt --black-status=401,400,404,500,503 --recursive "current.IsDir() && current.Status == 200"`

**Comment by M09Ic** [comment]
已确认问题, expr表达式库更新导致老的写法失效. 正在适配新的写法

**Comment by M09Ic** [comment]
![image](https://github.com/chainreactors/spray/assets/29176200/9e6ed38f-54bf-4f42-99eb-9fcc603fe4df)

**Comment by M09Ic** [comment]
因为暂时还没发布新办法, 可以尝试使用dev分支自行编译. 

联系方式可以邮件发送微信 m09ician@gmail.com 😊

**Comment by M09Ic** [comment]
done. https://github.com/chainreactors/spray/releases/tag/v0.9.8
