### ISSUE TITLE
input file is not working

### ISSUE THREAD

**Issue by channyein1337** [chainreactors/spray#4]
When I run spray with urls.txt , it is not working. The urls.txt contain list of urls with newline.

urls.txt
```
https://www.test.com
https://www.example.com
```

```
spray -l urls.txt -d /opt/wordlists/senfile.txt
[*] Retry Count: 1 , 2023-06-03 03:05.07
[*] Loaded 14018 word from /opt/wordlists/senfile.txt , 2023-06-03 03:05.07
[*] Parsed 14018 words by {?0} , 2023-06-03 03:05.07
[*] Loaded 0 urls from urls.txt , 2023-06-03 03:05.07
[*] Loaded 1 dictionaries and 0 decorators , 2023-06-03 03:05.07
```

**Comment by M09Ic** [comment]
Bugs have been fixed in pr: https://github.com/chainreactors/spray/pull/5 anda new release will be released as soon as possible.

**Comment by M09Ic** [comment]
Fixed, please download new release https://github.com/chainreactors/spray/releases/tag/v0.9.1
