### ISSUE TITLE
-o 失效

### ISSUE THREAD

**Issue by guanglianniubi** [chainreactors/spray#46]
使用-o筛选，还是出现md5，而且-o full输出的还是json格式

![628b4a46119e29f50f8bb47f1609b4b](https://github.com/user-attachments/assets/5c5443b3-c4d6-43b3-b6c4-b008e3872e34)

**Comment by M09Ic** [comment]
因为-f目前只会输出json格式。 需要在-F格式化时使用-o指定输出格式。 这点和gogo不太一样， gogo的输出设计的太复杂了，所以在spray中进行了简化
