### ISSUE TITLE
finger依旧报错

### ISSUE THREAD

**Issue by guanglianniubi** [chainreactors/spray#50]
![图片](https://github.com/user-attachments/assets/125bf837-d372-4c26-a164-512bd412f293)
命令：./spray_linux_amd64 -l ip.txt -d dic/dicc.txt --common --finger --crawl --bak --file-bak

**Comment by M09Ic** [comment]
似乎版本不是最新版? 因为新的版本fingers版本更新是0704 github.com/chainreactors/fingers v0.0.0-20240704063230-de8fec05ff8b
