### ISSUE TITLE
主动+爬虫

### ISSUE THREAD

**Issue by go-spider** [chainreactors/spray#6]
是先爬？还是主动和爬虫并行？先爬+js解析出一部分目录，可以减少爆破次数。

**Comment by M09Ic** [comment]
爬虫是一个单独的参数, 如果不设置字典， 例如 `spray -u http://example.com --crawl` 则仅爬虫. 

如果同时启用了字典与爬虫, 则是同时进行的.  如果想要减少爆破次数, 仅开启--crawl不设置字典即可.

**Comment by M09Ic** [comment]
目前spray已会自动去重, 已经请求过的目录不会跑第二遍. 

至于headless爬虫, 与spray本身的设计不适应. 如果有headless爬虫的需求, 可以使用katana 或 rad等.  

如果有spray与katana联动的思路欢迎提供新的issue.
