### ISSUE TITLE
卡住了

### ISSUE THREAD

**Issue by jinzezhi** [chainreactors/spray#7]
![image](https://github.com/chainreactors/spray/assets/93123422/2a51f36d-3ac4-475d-b85d-e0ae673fd2e6)
换了好几个url都是一直卡在这里

**Comment by jinzezhi** [comment]
抱歉，是我粗心了，url地址前没有加 -u 才会导致这样

**Comment by M09Ic** [comment]
后续没有正确添加参数会直接退出， 感谢提醒
