### ISSUE TITLE
异常了

### ISSUE THREAD

**Issue by ad-calcium** [chainreactors/spray#72]
![image](https://github.com/user-attachments/assets/a9185e01-bc80-4f3a-9080-def49e4f2a06)

**Comment by M09Ic** [comment]
是否可以提供命令行 ，让我可以更快定位bug

**Comment by ad-calcium** [comment]
spray -l url.txt -a

**Comment by M09Ic** [comment]
https://github.com/chainreactors/spray/releases/tag/v1.1.2
