### ISSUE TITLE
--remove-extension 和--replace 不起作用

### ISSUE THREAD

**Issue by Luoooio** [chainreactors/spray#8]
我在本地测试的时候发现--remove-extension 和不起作用
我的字典如下：
![image](https://github.com/chainreactors/spray/assets/26653157/0deacae1-bef4-4843-ba5a-67e790625d23)

我的命令如下:
![image](https://github.com/chainreactors/spray/assets/26653157/dce0efd9-ee6d-4c06-a3e3-de96fbeb08b4)
 
而我本地服务端收到的请求：
![image](https://github.com/chainreactors/spray/assets/26653157/fa61d6d6-3cec-4087-a8c1-b58d774c8d73)
并没有将我想删掉的扩展名给删掉。
而--exclude-extension可以正常工作。含有扩展的不会出现在请求中。
--replace 也无法正常工作。
![image](https://github.com/chainreactors/spray/assets/26653157/7779535a-9260-48e2-bf8e-c005bfa581af)

![image](https://github.com/chainreactors/spray/assets/26653157/43e6e91f-cacb-43b9-8bf1-395e88e71a8c)

**Comment by M09Ic** [comment]
--remove-extension 不生效的bug已确认， 将在下个版本修复 https://github.com/chainreactors/spray/pull/10

**Comment by M09Ic** [comment]
--replace 因为命令行解析库的限制, 不能使用`=`, 一定需要使用`:`作为分隔符. 例如 `--replace jsp:111`

**Comment by M09Ic** [comment]
新版本已修复https://github.com/chainreactors/spray/releases/tag/v0.9.2
